#!/usr/bin/env sh
# Deterministic local-refresh capture for the container-e2e golden real corpus.
#
# PROVENANCE — the canonical source of the committed real-corpus golden fixtures is now
# Timeweb S3, bucket `sg-replays`, key layout `raw/sha256/<hash>.ocap` (each object's name
# is the sha256 of its byte-exact content). The committed spread under
# crates/parser-core/tests/fixtures/golden/real/<hash>.ocap.gz was pulled from there
# (via an in-cluster minio/mc pod using `envFrom` the `replay-parser-2-runtime` config) on
# 2026-06-18, sha256-verified, and gzipped at rest. Their byte-exact baselines live in
# crates/parser-core/tests/fixtures/golden/expected/ and are regenerated by:
#   cargo test -p parser-core --test golden_artifact_bytes -- --ignored regenerate
#
# This script is the DOCUMENTED LOCAL-REFRESH FALLBACK: when Timeweb S3 is not reachable
# but a historical replay store is present at ~/sg_stats, it deterministically selects a
# small, PINNED, sorted, reproducible spread of real OCAP replays (one success, one
# partial/schema-drift, one failed/malformed, one large-entity), gzips each under
# crates/parser-worker/tests/fixtures/real/, and writes a manifest, so a human can refresh
# the corpus offline without the cluster.
#
# Run ONCE on a machine that has ~/sg_stats present:
#   sh scripts/capture-golden-replays.sh
#
# When ~/sg_stats is absent (e.g. CI or a fresh dev box) it prints a presence note and
# exits 0 — the e2e's own skip-guard covers fixture absence at test time, so `verify`
# stays green either way.
#
# NOTE: the committed real corpus is already gunzipped at runtime by the golden consumers
# (flate2 dev-dep wired in parser-core + parser-worker). This fallback writes the gz files
# + manifest; regenerate baselines with the parser-core `regenerate` test above.

set -eu

SG_STATS_DIR="${SG_STATS_DIR:-$HOME/sg_stats}"
REPO_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
REAL_DIR="$REPO_ROOT/crates/parser-worker/tests/fixtures/real"
# Commit only replays whose gzipped size is at or under this threshold (bytes).
MAX_COMPRESSED_BYTES="${MAX_COMPRESSED_BYTES:-262144}" # 256 KiB

if [ ! -d "$SG_STATS_DIR" ]; then
  echo "capture-golden-replays: ~/sg_stats not found at '$SG_STATS_DIR' — nothing to capture."
  echo "capture-golden-replays: run this on a machine with the historical replay store present."
  exit 0
fi

mkdir -p "$REAL_DIR"

# Deterministic selection: a sorted glob with fixed indices. Sorting guarantees the same
# set is chosen on every re-capture given the same source store.
SORTED_LIST="$(find "$SG_STATS_DIR" -type f -name '*.json' | LC_ALL=C sort)"
TOTAL="$(printf '%s\n' "$SORTED_LIST" | grep -c . || true)"

if [ "${TOTAL:-0}" -eq 0 ]; then
  echo "capture-golden-replays: no *.json replays under '$SG_STATS_DIR' — nothing to capture."
  exit 0
fi

echo "capture-golden-replays: $TOTAL candidate replays under '$SG_STATS_DIR'."

MANIFEST="$REAL_DIR/manifest.json"
: > "$MANIFEST.tmp"
printf '[\n' >> "$MANIFEST.tmp"
FIRST=1

# Pinned indices into the sorted list (1-based). Adjust deliberately if the curated
# spread must change; keep them small and stable so re-capture is reproducible.
#
# De-duplicated and bounded before the loop: when the store holds <=3 replays the raw
# set `1 2 3 $TOTAL` would repeat an index (e.g. TOTAL=3 -> `1 2 3 3`), emitting two
# manifest entries for the same fixture. `sort -n -u` collapses duplicates and the
# in-loop bound drops any index past the end, so each replay is captured at most once.
INDICES="$(printf '1\n2\n3\n%s\n' "$TOTAL" | sort -n -u)"
for IDX in $INDICES; do
  [ "$IDX" -le "$TOTAL" ] || continue
  SRC="$(printf '%s\n' "$SORTED_LIST" | sed -n "${IDX}p")"
  [ -n "$SRC" ] || continue
  BASE="$(basename "$SRC" .json)"
  GZ="$REAL_DIR/${BASE}.json.gz"
  gzip -c -n "$SRC" > "$GZ"
  CSIZE="$(wc -c < "$GZ" | tr -d ' ')"

  if [ "$CSIZE" -gt "$MAX_COMPRESSED_BYTES" ]; then
    echo "capture-golden-replays: SKIP '$BASE' — gzipped $CSIZE B exceeds ${MAX_COMPRESSED_BYTES} B; left uncommitted."
    rm -f "$GZ"
    continue
  fi

  [ "$FIRST" -eq 1 ] || printf ',\n' >> "$MANIFEST.tmp"
  FIRST=0
  printf '  { "fixture": "%s.json.gz", "source_file": "%s", "compressed_bytes": %s, "expected_status": "unverified" }' \
    "$BASE" "$(basename "$SRC")" "$CSIZE" >> "$MANIFEST.tmp"
  echo "capture-golden-replays: captured '$BASE' (${CSIZE} B gzipped)."
done

printf '\n]\n' >> "$MANIFEST.tmp"
mv "$MANIFEST.tmp" "$MANIFEST"

# Regenerate paired baselines from the pure parser so input+output are committed together.
# (Enabled once the gzip loader + flate2 dev-dep land with the real fixtures.)
echo "capture-golden-replays: wrote $MANIFEST."
echo "capture-golden-replays: regenerate baselines with the parser-core golden generator after wiring the gzip loader."
echo "capture-golden-replays: done."
